ccflags-y += -DDRV_VERSION="\"$$(sed -n -e 's/^Version:[[:blank:]]*\([^[:blank:]]*\).*/\1/p' $(KBUILD_EXTMOD)/../../../../ib_srp-backport.spec)\""
ccflags-y += -DDRV_RELDATE="\"$$(sed -n -e '/^%changelog/,/^-/ s/^\*[[:blank:]]*[^[:blank:]]*[[:blank:]]*\([^[:blank:]]*[[:blank:]]*[^[:blank:]]*[[:blank:]]*[^[:blank:]]*\).*/\1/p' $(KBUILD_EXTMOD)/../../../../ib_srp-backport.spec)\""

obj-$(CONFIG_INFINIBAND_SRP)			+= ib_srp.o
